export type DegreeType = 'B.Tech' | 'M.Tech' | 'MBA' | 'B.Sc' | 'M.Sc' | 'PhD' | 'BBA' | 'B.Com' | 'B.Arch';
export type CollegeType = 'Government' | 'Private' | 'Deemed';

export interface Review {
  id: string;
  author: string;
  avatar: string;
  rating: number;
  date: string;
  content: string;
  program: string;
  batch: string;
}

export interface College {
  id: string;
  name: string;
  shortName: string;
  logoColor: string;
  logoInitials: string;
  image: string;
  bannerImage: string;
  location: string;
  city: string;
  state: string;
  type: CollegeType;
  rating: number;
  reviewCount: number;
  annualFees: number;
  courses: string[];
  degreeTypes: DegreeType[];
  placementPercentage: number;
  averagePackage: number;
  highestPackage: number;
  nirfRanking: number;
  facilities: string[];
  accreditation: string;
  established: number;
  description: string;
  highlights: string[];
  topRecruiters: string[];
  reviews: Review[];
  specializations: string[];
  studentCount: number;
  facultyCount: number;
  campusArea: number;
}

const img = [
  'https://images.unsplash.com/photo-1575688588571-966e9b61f0b7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx1bml2ZXJzaXR5JTIwY2FtcHVzJTIwYnVpbGRpbmclMjBtb2Rlcm4lMjBhcmNoaXRlY3R1cmV8ZW58MXx8fHwxNzgwODkyNDM0fDA&ixlib=rb-4.1.0&q=80&w=1080',
  'https://images.unsplash.com/photo-1632988663082-4bac2c1847a0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwyfHx1bml2ZXJzaXR5JTIwY2FtcHVzJTIwYnVpbGRpbmclMjBtb2Rlcm4lMjBhcmNoaXRlY3R1cmV8ZW58MXx8fHwxNzgwODkyNDM0fDA&ixlib=rb-4.1.0&q=80&w=1080',
  'https://images.unsplash.com/photo-1598463035674-3ded88d65be2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwzfHx1bml2ZXJzaXR5JTIwY2FtcHVzJTIwYnVpbGRpbmclMjBtb2Rlcm4lMjBhcmNoaXRlY3R1cmV8ZW58MXx8fHwxNzgwODkyNDM0fDA&ixlib=rb-4.1.0&q=80&w=1080',
  'https://images.unsplash.com/photo-1734184489462-e8c123f2797b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHw0fHx1bml2ZXJzaXR5JTIwY2FtcHVzJTIwYnVpbGRpbmclMjBtb2Rlcm4lMjBhcmNoaXRlY3R1cmV8ZW58MXx8fHwxNzgwODkyNDM0fDA&ixlib=rb-4.1.0&q=80&w=1080',
  'https://images.unsplash.com/photo-1642552187855-388a77930fa8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHw1fHx1bml2ZXJzaXR5JTIwY2FtcHVzJTIwYnVpbGRpbmclMjBtb2Rlcm4lMjBhcmNoaXRlY3R1cmV8ZW58MXx8fHwxNzgwODkyNDM0fDA&ixlib=rb-4.1.0&q=80&w=1080',
  'https://images.unsplash.com/photo-1633987027569-a6599b632de7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHw2fHx1bml2ZXJzaXR5JTIwY2FtcHVzJTIwYnVpbGRpbmclMjBtb2Rlcm4lMjBhcmNoaXRlY3R1cmV8ZW58MXx8fHwxNzgwODkyNDM0fDA&ixlib=rb-4.1.0&q=80&w=1080',
  'https://images.unsplash.com/photo-1599043464895-0e273f94eed7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHw3fHx1bml2ZXJzaXR5JTIwY2FtcHVzJTIwYnVpbGRpbmclMjBtb2Rlcm4lMjBhcmNoaXRlY3R1cmV8ZW58MXx8fHwxNzgwODkyNDM0fDA&ixlib=rb-4.1.0&q=80&w=1080',
  'https://images.unsplash.com/photo-1664273891579-22f28332f3c4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHw4fHx1bml2ZXJzaXR5JTIwY2FtcHVzJTIwYnVpbGRpbmclMjBtb2Rlcm4lMjBhcmNoaXRlY3R1cmV8ZW58MXx8fHwxNzgwODkyNDM0fDA&ixlib=rb-4.1.0&q=80&w=1080',
];

export const colleges: College[] = [
  {
    id: 'iit-bombay',
    name: 'Indian Institute of Technology Bombay',
    shortName: 'IIT Bombay',
    logoColor: '#6366f1',
    logoInitials: 'IIT',
    image: img[0],
    bannerImage: img[0],
    location: 'Mumbai, Maharashtra',
    city: 'Mumbai',
    state: 'Maharashtra',
    type: 'Government',
    rating: 4.8,
    reviewCount: 2847,
    annualFees: 2.3,
    courses: ['Computer Science', 'Electrical Engineering', 'Mechanical Engineering', 'Chemical Engineering', 'Civil Engineering', 'Aerospace Engineering'],
    degreeTypes: ['B.Tech', 'M.Tech', 'PhD', 'M.Sc'],
    placementPercentage: 97,
    averagePackage: 24,
    highestPackage: 2.5,
    nirfRanking: 3,
    facilities: ['Library', 'Sports Complex', 'Hostel', 'Medical Center', 'Research Labs', 'Auditorium', 'Swimming Pool', 'Gymnasium'],
    accreditation: 'NAAC A++',
    established: 1958,
    description: 'IIT Bombay is one of India\'s premier engineering institutions, consistently ranked among the top universities in the country and Asia. Known for cutting-edge research, world-class faculty, and outstanding placement records across all streams.',
    highlights: ['#3 NIRF Ranking', '97% Placement Rate', 'QS World Rank 118', '₹2.5 Cr Highest Package'],
    topRecruiters: ['Google', 'Microsoft', 'Apple', 'Meta', 'Amazon', 'Goldman Sachs', 'McKinsey', 'BCG'],
    specializations: ['AI/ML', 'Data Science', 'VLSI Design', 'Robotics', 'Quantum Computing'],
    studentCount: 10000,
    facultyCount: 600,
    campusArea: 550,
    reviews: [
      { id: 'r1', author: 'Arjun Sharma', avatar: 'AS', rating: 5, date: 'March 2024', content: 'Exceptional research opportunities and world-class faculty. The placement cell is extremely active and the alumni network is unparalleled.', program: 'B.Tech CS', batch: '2024' },
      { id: 'r2', author: 'Priya Mehta', avatar: 'PM', rating: 4, date: 'January 2024', content: 'Great campus life and infrastructure. Curriculum is rigorous but rewarding. The research labs are state-of-the-art.', program: 'M.Tech', batch: '2023' },
      { id: 'r3', author: 'Rohan Iyer', avatar: 'RI', rating: 5, date: 'December 2023', content: 'Best decision of my life. The exposure you get here is unmatched. Companies love IIT Bombay graduates.', program: 'B.Tech EE', batch: '2023' },
    ],
  },
  {
    id: 'iit-delhi',
    name: 'Indian Institute of Technology Delhi',
    shortName: 'IIT Delhi',
    logoColor: '#3b82f6',
    logoInitials: 'IIT',
    image: img[1],
    bannerImage: img[1],
    location: 'New Delhi, Delhi',
    city: 'New Delhi',
    state: 'Delhi',
    type: 'Government',
    rating: 4.7,
    reviewCount: 3124,
    annualFees: 2.2,
    courses: ['Computer Science', 'Electrical Engineering', 'Mechanical Engineering', 'Physics', 'Mathematics', 'Management Studies'],
    degreeTypes: ['B.Tech', 'M.Tech', 'PhD', 'MBA', 'M.Sc'],
    placementPercentage: 96,
    averagePackage: 22,
    highestPackage: 2.1,
    nirfRanking: 2,
    facilities: ['Library', 'Sports Complex', 'Hostel', 'Medical Center', 'Research Labs', 'Auditorium', 'Swimming Pool'],
    accreditation: 'NAAC A++',
    established: 1961,
    description: 'IIT Delhi is consistently ranked #2 in India, known for its cutting-edge research programs and strong industry connections in the heart of the capital.',
    highlights: ['#2 NIRF Ranking', '96% Placement Rate', 'QS World Rank 197', 'Capital City Location'],
    topRecruiters: ['Google', 'Microsoft', 'Adobe', 'Qualcomm', 'Flipkart', 'Uber', 'LinkedIn', 'Morgan Stanley'],
    specializations: ['AI/ML', 'Cybersecurity', 'Photonics', 'Energy Systems', 'Finance'],
    studentCount: 8500,
    facultyCount: 540,
    campusArea: 325,
    reviews: [
      { id: 'r4', author: 'Rohit Verma', avatar: 'RV', rating: 5, date: 'February 2024', content: 'Being in Delhi gives phenomenal access to internship opportunities. The DMS management school is top-notch.', program: 'MBA', batch: '2024' },
      { id: 'r5', author: 'Sneha Kapoor', avatar: 'SK', rating: 4, date: 'November 2023', content: 'Excellent faculty and industry exposure. The campus has great connectivity and placement numbers speak for themselves.', program: 'B.Tech CSE', batch: '2023' },
    ],
  },
  {
    id: 'iisc',
    name: 'Indian Institute of Science',
    shortName: 'IISc Bangalore',
    logoColor: '#8b5cf6',
    logoInitials: 'IISc',
    image: img[2],
    bannerImage: img[2],
    location: 'Bangalore, Karnataka',
    city: 'Bangalore',
    state: 'Karnataka',
    type: 'Government',
    rating: 4.9,
    reviewCount: 1856,
    annualFees: 0.8,
    courses: ['Computer Science', 'Physics', 'Chemistry', 'Biology', 'Materials Engineering', 'Aerospace', 'Electrical'],
    degreeTypes: ['M.Sc', 'PhD', 'B.Sc'],
    placementPercentage: 91,
    averagePackage: 18,
    highestPackage: 1.8,
    nirfRanking: 1,
    facilities: ['World-class Research Labs', 'Library', 'Hostel', 'Medical', 'Sports', 'Canteen', 'Auditorium'],
    accreditation: 'NAAC A++',
    established: 1909,
    description: 'India\'s premier research institution, ranked #1 by NIRF. IISc focuses on science and engineering research and is known globally for breakthrough scientific discoveries.',
    highlights: ['#1 NIRF Ranking', 'Research Excellence', 'QS World Rank 155', 'Science & Research Focus'],
    topRecruiters: ['ISRO', 'DRDO', 'Intel Research', 'IBM Research', 'Google DeepMind', 'Siemens R&D'],
    specializations: ['Quantum Physics', 'Biosciences', 'Nanomaterials', 'Astrophysics', 'AI Research'],
    studentCount: 4200,
    facultyCount: 520,
    campusArea: 400,
    reviews: [
      { id: 'r6', author: 'Kavita Nair', avatar: 'KN', rating: 5, date: 'April 2024', content: 'Best research environment in India. Resources and facilities are unmatched globally. Perfect for PhD students.', program: 'PhD CS', batch: '2023' },
    ],
  },
  {
    id: 'bits-pilani',
    name: 'BITS Pilani',
    shortName: 'BITS Pilani',
    logoColor: '#ef4444',
    logoInitials: 'BITS',
    image: img[3],
    bannerImage: img[3],
    location: 'Pilani, Rajasthan',
    city: 'Pilani',
    state: 'Rajasthan',
    type: 'Deemed',
    rating: 4.6,
    reviewCount: 4215,
    annualFees: 5.2,
    courses: ['Computer Science', 'Electronics', 'Mechanical', 'Chemical', 'Mathematics', 'Pharmacy', 'Economics', 'Finance'],
    degreeTypes: ['B.Tech', 'M.Tech', 'PhD', 'MBA', 'B.Sc'],
    placementPercentage: 92,
    averagePackage: 16,
    highestPackage: 1.5,
    nirfRanking: 23,
    facilities: ['Library', 'Sports Complex', 'Hostel', 'Medical', 'Labs', 'Multiple Canteens', 'Auditorium', 'Gym'],
    accreditation: 'NAAC A',
    established: 1964,
    description: 'BITS Pilani is India\'s top private engineering institution with a unique Practice School program offering guaranteed industry internships. Known for an exceptional alumni network.',
    highlights: ['Top Private University', '92% Placement', 'Practice School Program', 'Global Alumni Network'],
    topRecruiters: ['Microsoft', 'Google', 'Amazon', 'Samsung R&D', 'Qualcomm', 'Cisco', 'Goldman Sachs'],
    specializations: ['Software Engineering', 'VLSI Design', 'Quantitative Finance', 'Data Science'],
    studentCount: 6000,
    facultyCount: 380,
    campusArea: 180,
    reviews: [
      { id: 'r7', author: 'Nikhil Agarwal', avatar: 'NA', rating: 4, date: 'January 2024', content: 'Autonomous curriculum lets you choose courses freely. Practice School gives real industry experience that no other college provides.', program: 'B.Tech CS', batch: '2024' },
    ],
  },
  {
    id: 'nit-trichy',
    name: 'National Institute of Technology Tiruchirappalli',
    shortName: 'NIT Trichy',
    logoColor: '#0891b2',
    logoInitials: 'NIT',
    image: img[4],
    bannerImage: img[4],
    location: 'Tiruchirappalli, Tamil Nadu',
    city: 'Tiruchirappalli',
    state: 'Tamil Nadu',
    type: 'Government',
    rating: 4.5,
    reviewCount: 2651,
    annualFees: 1.8,
    courses: ['Computer Science', 'Mechanical', 'Civil', 'Electrical', 'Electronics', 'Production Engineering'],
    degreeTypes: ['B.Tech', 'M.Tech', 'PhD', 'M.Sc'],
    placementPercentage: 89,
    averagePackage: 12,
    highestPackage: 0.85,
    nirfRanking: 9,
    facilities: ['Library', 'Sports Complex', 'Hostel', 'Research Labs', 'Medical', 'Auditorium', 'Swimming Pool'],
    accreditation: 'NAAC A++',
    established: 1964,
    description: 'NIT Trichy is consistently ranked among the top NITs in India. Known for its rigorous curriculum, strong research programs and excellent placement record in core engineering.',
    highlights: ['#9 NIRF Ranking', '89% Placement', 'Best NIT South India', 'Strong Core Companies'],
    topRecruiters: ['Tata Steel', 'L&T', 'Infosys', 'TCS', 'Wipro', 'Deloitte', 'Hyundai Motor', 'ABB'],
    specializations: ['Manufacturing', 'Power Systems', 'Structural Engineering', 'Thermal Engineering'],
    studentCount: 5800,
    facultyCount: 420,
    campusArea: 800,
    reviews: [],
  },
  {
    id: 'vit-vellore',
    name: 'Vellore Institute of Technology',
    shortName: 'VIT Vellore',
    logoColor: '#d97706',
    logoInitials: 'VIT',
    image: img[5],
    bannerImage: img[5],
    location: 'Vellore, Tamil Nadu',
    city: 'Vellore',
    state: 'Tamil Nadu',
    type: 'Deemed',
    rating: 4.2,
    reviewCount: 7821,
    annualFees: 2.4,
    courses: ['Computer Science', 'IT', 'Biotech', 'Mechanical', 'ECE', 'Civil', 'Chemistry', 'Pharmacy'],
    degreeTypes: ['B.Tech', 'M.Tech', 'PhD', 'MBA', 'M.Sc'],
    placementPercentage: 84,
    averagePackage: 7.5,
    highestPackage: 0.5,
    nirfRanking: 11,
    facilities: ['Library', 'Sports Complex', 'Hostel', 'Hospitals', 'Labs', 'Food Court', 'Gym', 'Auditorium'],
    accreditation: 'NAAC A++',
    established: 1984,
    description: 'VIT Vellore is one of India\'s largest private universities with excellent global partnerships and a strong focus on research and innovation across disciplines.',
    highlights: ['#11 NIRF', '84% Placement', '50+ International MoUs', 'Large Innovation Campus'],
    topRecruiters: ['Cognizant', 'Infosys', 'TCS', 'Wipro', 'Capgemini', 'Accenture', 'Zoho', 'Freshworks'],
    specializations: ['Cloud Computing', 'Bioinformatics', 'Embedded Systems', 'IoT'],
    studentCount: 28000,
    facultyCount: 2200,
    campusArea: 350,
    reviews: [],
  },
  {
    id: 'manipal',
    name: 'Manipal Institute of Technology',
    shortName: 'MIT Manipal',
    logoColor: '#059669',
    logoInitials: 'MIT',
    image: img[6],
    bannerImage: img[6],
    location: 'Manipal, Karnataka',
    city: 'Manipal',
    state: 'Karnataka',
    type: 'Deemed',
    rating: 4.1,
    reviewCount: 5640,
    annualFees: 4.0,
    courses: ['Computer Science', 'Mechanical', 'Civil', 'ECE', 'IT', 'Chemical', 'Industrial Engineering'],
    degreeTypes: ['B.Tech', 'M.Tech', 'PhD', 'MBA'],
    placementPercentage: 80,
    averagePackage: 6.5,
    highestPackage: 0.4,
    nirfRanking: 35,
    facilities: ['Beach Campus', 'Library', 'Sports', 'Hostel', 'Medical College', 'Hospital', 'Innovation Labs'],
    accreditation: 'NAAC A++',
    established: 1957,
    description: 'MIT Manipal is part of Manipal Academy of Higher Education, offering excellent engineering programs with a picturesque coastal campus and healthcare ecosystem.',
    highlights: ['Coastal Campus', 'Healthcare Ecosystem', '80% Placement', 'International Programs'],
    topRecruiters: ['Infosys', 'TCS', 'HCL', 'Bosch', 'Shell', 'Siemens', 'ABB', 'Honeywell'],
    specializations: ['Mechatronics', 'Health Informatics', 'Marine Engineering', 'Automation'],
    studentCount: 15000,
    facultyCount: 1100,
    campusArea: 600,
    reviews: [],
  },
  {
    id: 'srm',
    name: 'SRM Institute of Science and Technology',
    shortName: 'SRM University',
    logoColor: '#9333ea',
    logoInitials: 'SRM',
    image: img[7],
    bannerImage: img[7],
    location: 'Chennai, Tamil Nadu',
    city: 'Chennai',
    state: 'Tamil Nadu',
    type: 'Deemed',
    rating: 3.9,
    reviewCount: 9342,
    annualFees: 2.8,
    courses: ['Computer Science', 'IT', 'ECE', 'Mechanical', 'Civil', 'Biotech', 'MBA', 'BBA'],
    degreeTypes: ['B.Tech', 'M.Tech', 'PhD', 'MBA', 'BBA'],
    placementPercentage: 78,
    averagePackage: 5.5,
    highestPackage: 0.35,
    nirfRanking: 24,
    facilities: ['Library', 'Hospital', 'Hostel', 'Sports Complex', 'Labs', 'Auditorium', 'Cafeteria'],
    accreditation: 'NAAC A++',
    established: 1985,
    description: 'SRM University is a large private university known for its diverse programs, strong industry collaborations, and excellent placement support system.',
    highlights: ['78% Placement', 'Large Industry Network', 'Multiple Campuses', 'Diverse Programs'],
    topRecruiters: ['TCS', 'Wipro', 'CTS', 'Infosys', 'Hexaware', 'Accenture', 'HCL', 'Tech Mahindra'],
    specializations: ['Cloud Services', 'IoT', 'Data Analytics', 'Digital Marketing'],
    studentCount: 50000,
    facultyCount: 3500,
    campusArea: 250,
    reviews: [],
  },
  {
    id: 'iiit-hyderabad',
    name: 'International Institute of Information Technology Hyderabad',
    shortName: 'IIIT Hyderabad',
    logoColor: '#1e40af',
    logoInitials: 'IIIT',
    image: img[0],
    bannerImage: img[0],
    location: 'Hyderabad, Telangana',
    city: 'Hyderabad',
    state: 'Telangana',
    type: 'Deemed',
    rating: 4.4,
    reviewCount: 1890,
    annualFees: 3.5,
    courses: ['Computer Science', 'Electronics', 'Data Science', 'Computational Linguistics', 'Cognitive Science', 'AI'],
    degreeTypes: ['B.Tech', 'M.Tech', 'PhD', 'M.Sc'],
    placementPercentage: 93,
    averagePackage: 20,
    highestPackage: 2.0,
    nirfRanking: 30,
    facilities: ['Research Labs', 'Library', 'Hostel', 'Sports', 'Cafeteria', 'Innovation Center'],
    accreditation: 'NAAC A',
    established: 1998,
    description: 'IIIT Hyderabad is a research university specializing in IT and related sciences. Known for cutting-edge AI/ML research and outstanding software engineering placements.',
    highlights: ['AI Research Hub', '93% Placement', 'Research-First Approach', 'Top Software Salaries'],
    topRecruiters: ['Google', 'Microsoft', 'Amazon', 'Adobe', 'Qualcomm', 'Oracle', 'Goldman Sachs', 'Uber'],
    specializations: ['AI/ML', 'NLP', 'Computer Vision', 'Human-Computer Interaction', 'Robotics'],
    studentCount: 3200,
    facultyCount: 180,
    campusArea: 66,
    reviews: [],
  },
  {
    id: 'anna-university',
    name: 'Anna University',
    shortName: 'Anna University',
    logoColor: '#b45309',
    logoInitials: 'AU',
    image: img[1],
    bannerImage: img[1],
    location: 'Chennai, Tamil Nadu',
    city: 'Chennai',
    state: 'Tamil Nadu',
    type: 'Government',
    rating: 4.0,
    reviewCount: 6234,
    annualFees: 0.95,
    courses: ['Computer Science', 'ECE', 'Mechanical', 'Civil', 'Chemical', 'IT', 'Architecture'],
    degreeTypes: ['B.Tech', 'M.Tech', 'PhD', 'B.Arch', 'M.Sc'],
    placementPercentage: 75,
    averagePackage: 5,
    highestPackage: 0.3,
    nirfRanking: 19,
    facilities: ['Library', 'Labs', 'Sports', 'Hostel', 'Medical', 'Auditorium'],
    accreditation: 'NAAC A++',
    established: 1978,
    description: 'Anna University is the flagship government university for engineering in Tamil Nadu. Its main campus is a research and teaching hub for thousands of students.',
    highlights: ['Government University', 'Affordable Fees', '#19 NIRF', 'Tamil Nadu Flagship'],
    topRecruiters: ['Infosys', 'TCS', 'HCL', 'BHEL', 'TNEB', 'L&T', 'Ashok Leyland'],
    specializations: ['Civil Infrastructure', 'Power Engineering', 'Embedded Systems'],
    studentCount: 6000,
    facultyCount: 450,
    campusArea: 185,
    reviews: [],
  },
  {
    id: 'nit-warangal',
    name: 'National Institute of Technology Warangal',
    shortName: 'NIT Warangal',
    logoColor: '#1d4ed8',
    logoInitials: 'NIT',
    image: img[2],
    bannerImage: img[2],
    location: 'Warangal, Telangana',
    city: 'Warangal',
    state: 'Telangana',
    type: 'Government',
    rating: 4.3,
    reviewCount: 2145,
    annualFees: 1.7,
    courses: ['Computer Science', 'ECE', 'Mechanical', 'Civil', 'Chemical', 'Metallurgy', 'Management'],
    degreeTypes: ['B.Tech', 'M.Tech', 'PhD', 'MBA'],
    placementPercentage: 87,
    averagePackage: 11,
    highestPackage: 0.7,
    nirfRanking: 18,
    facilities: ['Library', 'Labs', 'Sports Complex', 'Hostel', 'Medical', 'Gymnasium'],
    accreditation: 'NAAC A++',
    established: 1959,
    description: 'NIT Warangal is one of the oldest and most prestigious NITs with a strong reputation for engineering education and research in core engineering disciplines.',
    highlights: ['#18 NIRF', '87% Placement', 'Oldest NIT South India', 'Core Engineering Excellence'],
    topRecruiters: ['Amazon', 'Deloitte', 'Capgemini', 'BHEL', 'Microsoft', 'Wipro', 'TCS'],
    specializations: ['Metallurgy', 'Water Resources', 'Power Electronics', 'Structural Engineering'],
    studentCount: 5000,
    facultyCount: 360,
    campusArea: 250,
    reviews: [],
  },
  {
    id: 'jadavpur',
    name: 'Jadavpur University',
    shortName: 'JU Kolkata',
    logoColor: '#166534',
    logoInitials: 'JU',
    image: img[3],
    bannerImage: img[3],
    location: 'Kolkata, West Bengal',
    city: 'Kolkata',
    state: 'West Bengal',
    type: 'Government',
    rating: 4.2,
    reviewCount: 3287,
    annualFees: 0.5,
    courses: ['Computer Science', 'Electrical Engineering', 'Civil', 'Mechanical', 'Chemical', 'Pharmaceutical Technology'],
    degreeTypes: ['B.Tech', 'M.Tech', 'PhD', 'M.Sc', 'B.Sc'],
    placementPercentage: 82,
    averagePackage: 9,
    highestPackage: 0.55,
    nirfRanking: 12,
    facilities: ['Library', 'Labs', 'Hostel', 'Sports', 'Cultural Centers', 'Auditorium'],
    accreditation: 'NAAC A',
    established: 1955,
    description: 'Jadavpur University is a premier state university in Eastern India known for its excellent engineering and science programs and vibrant student culture.',
    highlights: ['#12 NIRF', 'Most Affordable', 'Strong Research Culture', 'Best East India'],
    topRecruiters: ['TCS', 'Wipro', 'Infosys', 'ONGC', 'Coal India', 'HCL', 'Tata Motors'],
    specializations: ['Chemical Process', 'Power Systems', 'Control Engineering'],
    studentCount: 14000,
    facultyCount: 750,
    campusArea: 90,
    reviews: [],
  },
];

export const popularSearches = [
  'Computer Science Engineering',
  'IIT Colleges Delhi',
  'Top Engineering Bangalore',
  'Government Colleges Maharashtra',
  'Best Placement Colleges',
  'Architecture Programs',
  'MBA Top Colleges',
  'Affordable Engineering',
];

export const featuredColleges = colleges.slice(0, 8);
export const trendingColleges = colleges.slice(0, 6);
