export type DegreeType = 'B.Tech' | 'M.Tech' | 'MBA' | 'B.Sc' | 'M.Sc' | 'PhD' | 'BBA' | 'B.Com' | 'B.Arch' | 'MBBS' | 'B.Des';
export type CollegeType = 'Government' | 'Private' | 'Deemed';

export interface Review {
  id: string;
  author: string;
  avatar: string;
  rating: number;
  date: string;
  content: string;
  program: string;
  batch: string;
}

export interface College {
  id: string;
  name: string;
  shortName: string;
  logoColor: string;
  logoInitials: string;
  image: string;
  bannerImage: string;
  location: string;
  city: string;
  state: string;
  type: CollegeType;
  rating: number;
  reviewCount: number;
  annualFees: number;
  courses: string[];
  degreeTypes: DegreeType[];
  placementPercentage: number;
  averagePackage: number;
  highestPackage: number;
  nirfRanking: number;
  facilities: string[];
  accreditation: string;
  established: number;
  description: string;
  highlights: string[];
  topRecruiters: string[];
  reviews: Review[];
  specializations: string[];
  studentCount: number;
  facultyCount: number;
  campusArea: number;
}

export const colleges: College[] = [
  {
    id: 'fms-delhi',
    name: 'Faculty of Management Studies',
    shortName: 'FMS Delhi',
    logoColor: '#6366f1',
    logoInitials: 'FMS',
    image: 'https://images.unsplash.com/photo-1575688588571-966e9b61f0b7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    bannerImage: 'https://images.unsplash.com/photo-1575688588571-966e9b61f0b7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    location: 'New Delhi, Delhi',
    city: 'New Delhi',
    state: 'Delhi',
    type: 'Government',
    rating: 4.9,
    reviewCount: 1540,
    annualFees: 1.0,
    courses: ['MBA', 'Executive MBA'],
    degreeTypes: ['MBA', 'PhD'],
    placementPercentage: 100,
    averagePackage: 34.0,
    highestPackage: 58.0,
    nirfRanking: 15,
    facilities: ['Library', 'Hostel', 'Seminar Halls'],
    accreditation: 'UGC',
    established: 1954,
    description: 'FMS Delhi is one of the top business schools in India, known for its incredible ROI and stellar placements.',
    highlights: ['Best ROI', 'Top 15 NIRF', '100% Placement'],
    topRecruiters: ['McKinsey', 'BCG', 'Bain', 'TAS', 'HUL'],
    specializations: ['Marketing', 'Finance', 'Strategy'],
    studentCount: 500,
    facultyCount: 50,
    campusArea: 10,
    reviews: [],
  },
  {
    id: 'iit-madras',
    name: 'Indian Institute of Technology Madras',
    shortName: 'IIT Madras',
    logoColor: '#ef4444',
    logoInitials: 'IIT',
    image: 'https://images.unsplash.com/photo-1632988663082-4bac2c1847a0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    bannerImage: 'https://images.unsplash.com/photo-1632988663082-4bac2c1847a0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    location: 'Chennai, Tamil Nadu',
    city: 'Chennai',
    state: 'Tamil Nadu',
    type: 'Government',
    rating: 4.9,
    reviewCount: 3200,
    annualFees: 2.1,
    courses: ['Computer Science', 'Mechanical Engineering', 'Civil Engineering'],
    degreeTypes: ['B.Tech', 'M.Tech', 'PhD'],
    placementPercentage: 94,
    averagePackage: 21.5,
    highestPackage: 198.0,
    nirfRanking: 1,
    facilities: ['Research Park', 'Library', 'Hostel', 'Sports Complex'],
    accreditation: 'NAAC A++',
    established: 1959,
    description: 'IIT Madras is the top-ranked engineering institution in India, known for its innovation and research park.',
    highlights: ['#1 NIRF Ranking', '198 LPA Highest Package', 'Incubation Center'],
    topRecruiters: ['Google', 'Microsoft', 'Jane Street', 'Apple', 'Tower Research'],
    specializations: ['AI/ML', 'Robotics', 'Quantum Computing'],
    studentCount: 11000,
    facultyCount: 650,
    campusArea: 617,
    reviews: [],
  },
  {
    id: 'iim-ahmedabad',
    name: 'Indian Institute of Management Ahmedabad',
    shortName: 'IIM Ahmedabad',
    logoColor: '#059669',
    logoInitials: 'IIM',
    image: 'https://images.unsplash.com/photo-1598463035674-3ded88d65be2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    bannerImage: 'https://images.unsplash.com/photo-1598463035674-3ded88d65be2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    location: 'Ahmedabad, Gujarat',
    city: 'Ahmedabad',
    state: 'Gujarat',
    type: 'Government',
    rating: 4.9,
    reviewCount: 2100,
    annualFees: 15.0,
    courses: ['PGP', 'PGPX', 'FABM'],
    degreeTypes: ['MBA', 'PhD'],
    placementPercentage: 100,
    averagePackage: 32.0,
    highestPackage: 115.0,
    nirfRanking: 1,
    facilities: ['Vikram Sarabhai Library', 'Hostel', 'Sports Complex'],
    accreditation: 'EQUIS',
    established: 1961,
    description: 'IIM Ahmedabad is India\'s premier management institute, producing top business leaders globally.',
    highlights: ['#1 Management Institute', 'EQUIS Accredited', 'Global Alumni'],
    topRecruiters: ['McKinsey', 'BCG', 'Bain', 'Goldman Sachs', 'Morgan Stanley'],
    specializations: ['Finance', 'Strategy', 'Marketing'],
    studentCount: 1000,
    facultyCount: 100,
    campusArea: 102,
    reviews: [],
  },
  {
    id: 'isb-hyderabad',
    name: 'Indian School of Business',
    shortName: 'ISB Hyderabad',
    logoColor: '#f59e0b',
    logoInitials: 'ISB',
    image: 'https://images.unsplash.com/photo-1734184489462-e8c123f2797b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    bannerImage: 'https://images.unsplash.com/photo-1734184489462-e8c123f2797b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    location: 'Hyderabad, Telangana',
    city: 'Hyderabad',
    state: 'Telangana',
    type: 'Private',
    rating: 4.9,
    reviewCount: 1800,
    annualFees: 25.0,
    courses: ['PGP', 'PGPMAX'],
    degreeTypes: ['MBA'],
    placementPercentage: 100,
    averagePackage: 34.0,
    highestPackage: 60.0,
    nirfRanking: 1,
    facilities: ['Library', 'Hostel', 'Sports Complex'],
    accreditation: 'EQUIS',
    established: 2001,
    description: 'ISB is a world-class business school in India offering top-tier management education.',
    highlights: ['Global Faculty', '1 Year PGP', 'EQUIS Accredited'],
    topRecruiters: ['McKinsey', 'BCG', 'Bain', 'Google', 'Microsoft'],
    specializations: ['Finance', 'Strategy', 'Marketing'],
    studentCount: 900,
    facultyCount: 80,
    campusArea: 260,
    reviews: [],
  },
  {
    id: 'iisc-bangalore',
    name: 'Indian Institute of Science',
    shortName: 'IISc Bangalore',
    logoColor: '#3b82f6',
    logoInitials: 'IISC',
    image: 'https://images.unsplash.com/photo-1642552187855-388a77930fa8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    bannerImage: 'https://images.unsplash.com/photo-1642552187855-388a77930fa8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    location: 'Bangalore, Karnataka',
    city: 'Bangalore',
    state: 'Karnataka',
    type: 'Government',
    rating: 4.9,
    reviewCount: 2200,
    annualFees: 0.35,
    courses: ['B.Sc (Research)', 'M.Tech', 'PhD'],
    degreeTypes: ['B.Sc', 'M.Tech', 'PhD'],
    placementPercentage: 98,
    averagePackage: 28.0,
    highestPackage: 85.0,
    nirfRanking: 1,
    facilities: ['Library', 'Hostel', 'Research Labs'],
    accreditation: 'NAAC A++',
    established: 1909,
    description: 'IISc is India\'s premier institute for advanced scientific and technological research.',
    highlights: ['#1 University in India', 'Research Focus', 'Global Faculty'],
    topRecruiters: ['Intel', 'IBM Research', 'Google', 'Microsoft'],
    specializations: ['Deep Tech', 'AI/ML', 'Quantum Computing'],
    studentCount: 4000,
    facultyCount: 500,
    campusArea: 400,
    reviews: [],
  },
  {
    id: 'aiims-delhi',
    name: 'All India Institute of Medical Sciences',
    shortName: 'AIIMS New Delhi',
    logoColor: '#10b981',
    logoInitials: 'AIIMS',
    image: 'https://images.unsplash.com/photo-1633987027569-a6599b632de7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    bannerImage: 'https://images.unsplash.com/photo-1633987027569-a6599b632de7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    location: 'New Delhi, Delhi',
    city: 'New Delhi',
    state: 'Delhi',
    type: 'Government',
    rating: 4.9,
    reviewCount: 3500,
    annualFees: 0.02,
    courses: ['MBBS', 'MD', 'MS'],
    degreeTypes: ['MBBS', 'PhD'],
    placementPercentage: 100,
    averagePackage: 18.0,
    highestPackage: 40.0,
    nirfRanking: 1,
    facilities: ['Library', 'Hostel', 'Hospital'],
    accreditation: 'NMC',
    established: 1956,
    description: 'AIIMS New Delhi is the apex medical research and public hospital in India.',
    highlights: ['#1 Medical College', 'Apex Hospital', 'Global Recognition'],
    topRecruiters: ['AIIMS', 'Apollo', 'Fortis', 'Max Healthcare'],
    specializations: ['Surgery', 'Medicine', 'Pediatrics'],
    studentCount: 3000,
    facultyCount: 600,
    campusArea: 214,
    reviews: [],
  },
  {
    id: 'iit-bombay',
    name: 'Indian Institute of Technology Bombay',
    shortName: 'IIT Bombay',
    logoColor: '#ef4444',
    logoInitials: 'IITB',
    image: 'https://images.unsplash.com/photo-1599043464895-0e273f94eed7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    bannerImage: 'https://images.unsplash.com/photo-1599043464895-0e273f94eed7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    location: 'Mumbai, Maharashtra',
    city: 'Mumbai',
    state: 'Maharashtra',
    type: 'Government',
    rating: 4.8,
    reviewCount: 3100,
    annualFees: 2.30,
    courses: ['Computer Science', 'Electrical', 'Mechanical'],
    degreeTypes: ['B.Tech', 'M.Tech', 'PhD'],
    placementPercentage: 95,
    averagePackage: 21.8,
    highestPackage: 367.0,
    nirfRanking: 3,
    facilities: ['Library', 'Hostel', 'Sports Complex'],
    accreditation: 'NAAC A++',
    established: 1958,
    description: 'IIT Bombay is a globally acclaimed engineering institute located in the financial capital of India.',
    highlights: ['Top 3 NIRF', 'Highest Packages', 'Entrepreneurship'],
    topRecruiters: ['Jane Street', 'Optiver', 'Google', 'Microsoft'],
    specializations: ['Computer Science', 'AI', 'Fintech'],
    studentCount: 10000,
    facultyCount: 600,
    campusArea: 550,
    reviews: [],
  },
  {
    id: 'iim-bangalore',
    name: 'Indian Institute of Management Bangalore',
    shortName: 'IIM Bangalore',
    logoColor: '#059669',
    logoInitials: 'IIMB',
    image: 'https://images.unsplash.com/photo-1664273891579-22f28332f3c4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    bannerImage: 'https://images.unsplash.com/photo-1664273891579-22f28332f3c4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    location: 'Bangalore, Karnataka',
    city: 'Bangalore',
    state: 'Karnataka',
    type: 'Government',
    rating: 4.8,
    reviewCount: 2000,
    annualFees: 12.25,
    courses: ['PGP', 'PGPEM', 'EPGP'],
    degreeTypes: ['MBA', 'PhD'],
    placementPercentage: 100,
    averagePackage: 35.0,
    highestPackage: 115.0,
    nirfRanking: 2,
    facilities: ['Library', 'Hostel', 'Sports Complex'],
    accreditation: 'EQUIS',
    established: 1973,
    description: 'IIM Bangalore is celebrated for its excellent management programs and location in India\'s tech hub.',
    highlights: ['#2 Management Institute', 'Global Alumni', 'Tech Ecosystem'],
    topRecruiters: ['McKinsey', 'BCG', 'Bain', 'Amazon', 'Microsoft'],
    specializations: ['Strategy', 'Finance', 'Analytics'],
    studentCount: 1200,
    facultyCount: 110,
    campusArea: 100,
    reviews: [],
  },
  {
    id: 'iit-kanpur',
    name: 'Indian Institute of Technology Kanpur',
    shortName: 'IIT Kanpur',
    logoColor: '#ef4444',
    logoInitials: 'IITK',
    image: 'https://images.unsplash.com/photo-1575688588571-966e9b61f0b7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    bannerImage: 'https://images.unsplash.com/photo-1575688588571-966e9b61f0b7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    location: 'Kanpur, Uttar Pradesh',
    city: 'Kanpur',
    state: 'Uttar Pradesh',
    type: 'Government',
    rating: 4.8,
    reviewCount: 2500,
    annualFees: 2.20,
    courses: ['Computer Science', 'Aerospace', 'Mechanical'],
    degreeTypes: ['B.Tech', 'M.Tech', 'PhD'],
    placementPercentage: 92,
    averagePackage: 20.0,
    highestPackage: 190.0,
    nirfRanking: 4,
    facilities: ['Flight Lab', 'Library', 'Hostel'],
    accreditation: 'NAAC A',
    established: 1959,
    description: 'IIT Kanpur is renowned for its rigorous academic curriculum and research excellence.',
    highlights: ['Top 5 NIRF', 'Flight Lab', 'Strong Alumni Network'],
    topRecruiters: ['Google', 'Microsoft', 'Amazon', 'Tower Research'],
    specializations: ['Computer Science', 'Aerospace', 'Data Science'],
    studentCount: 8000,
    facultyCount: 500,
    campusArea: 1055,
    reviews: [],
  },
  {
    id: 'iit-kharagpur',
    name: 'Indian Institute of Technology Kharagpur',
    shortName: 'IIT Kharagpur',
    logoColor: '#ef4444',
    logoInitials: 'IITKGP',
    image: 'https://images.unsplash.com/photo-1632988663082-4bac2c1847a0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    bannerImage: 'https://images.unsplash.com/photo-1632988663082-4bac2c1847a0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    location: 'Kharagpur, West Bengal',
    city: 'Kharagpur',
    state: 'West Bengal',
    type: 'Government',
    rating: 4.8,
    reviewCount: 3300,
    annualFees: 2.20,
    courses: ['Computer Science', 'Electrical', 'Mining'],
    degreeTypes: ['B.Tech', 'M.Tech', 'PhD'],
    placementPercentage: 90,
    averagePackage: 19.0,
    highestPackage: 240.0,
    nirfRanking: 6,
    facilities: ['Library', 'Hostel', 'Sports Complex'],
    accreditation: 'NAAC A',
    established: 1951,
    description: 'IIT Kharagpur is the first IIT established and boasts the largest campus among all IITs.',
    highlights: ['Oldest IIT', 'Largest Campus', 'Strong Alumni'],
    topRecruiters: ['Google', 'Microsoft', 'Amazon', 'Barclays'],
    specializations: ['Computer Science', 'Mining', 'Architecture'],
    studentCount: 12000,
    facultyCount: 700,
    campusArea: 2100,
    reviews: [],
  },
  {
    id: 'bits-pilani',
    name: 'Birla Institute of Technology and Science',
    shortName: 'BITS Pilani',
    logoColor: '#8b5cf6',
    logoInitials: 'BITS',
    image: 'https://images.unsplash.com/photo-1598463035674-3ded88d65be2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    bannerImage: 'https://images.unsplash.com/photo-1598463035674-3ded88d65be2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    location: 'Pilani, Rajasthan',
    city: 'Pilani',
    state: 'Rajasthan',
    type: 'Private',
    rating: 4.8,
    reviewCount: 2800,
    annualFees: 5.50,
    courses: ['Computer Science', 'Electrical', 'Mechanical'],
    degreeTypes: ['B.Tech', 'M.Tech', 'PhD'],
    placementPercentage: 98,
    averagePackage: 20.0,
    highestPackage: 60.0,
    nirfRanking: 20,
    facilities: ['Library', 'Hostel', 'Innovation Center'],
    accreditation: 'NAAC A',
    established: 1964,
    description: 'BITS Pilani is a premier private engineering institute with a strong focus on entrepreneurship and innovation.',
    highlights: ['0% Attendance Rule', 'Entrepreneurship', 'Practice School'],
    topRecruiters: ['Google', 'Microsoft', 'Amazon', 'Uber'],
    specializations: ['Computer Science', 'Electronics', 'Finance'],
    studentCount: 5000,
    facultyCount: 350,
    campusArea: 328,
    reviews: [],
  },
  {
    id: 'iiit-hyderabad',
    name: 'International Institute of Information Technology',
    shortName: 'IIIT Hyderabad',
    logoColor: '#0ea5e9',
    logoInitials: 'IIITH',
    image: 'https://images.unsplash.com/photo-1734184489462-e8c123f2797b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    bannerImage: 'https://images.unsplash.com/photo-1734184489462-e8c123f2797b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    location: 'Hyderabad, Telangana',
    city: 'Hyderabad',
    state: 'Telangana',
    type: 'Private',
    rating: 4.8,
    reviewCount: 1500,
    annualFees: 3.60,
    courses: ['Computer Science', 'Electronics'],
    degreeTypes: ['B.Tech', 'M.Tech', 'PhD'],
    placementPercentage: 100,
    averagePackage: 30.0,
    highestPackage: 74.0,
    nirfRanking: 55,
    facilities: ['Research Centers', 'Library', 'Hostel'],
    accreditation: 'NAAC A',
    established: 1998,
    description: 'IIIT Hyderabad is widely regarded as the best institute in India for Computer Science research and coding culture.',
    highlights: ['Best Coding Culture', '100% Placements', 'Research Focus'],
    topRecruiters: ['Apple', 'Google', 'Microsoft', 'Tower Research'],
    specializations: ['Computer Science', 'AI', 'Robotics'],
    studentCount: 1800,
    facultyCount: 100,
    campusArea: 66,
    reviews: [],
  },
  {
    id: 'iim-lucknow',
    name: 'Indian Institute of Management Lucknow',
    shortName: 'IIM Lucknow',
    logoColor: '#059669',
    logoInitials: 'IIML',
    image: 'https://images.unsplash.com/photo-1642552187855-388a77930fa8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    bannerImage: 'https://images.unsplash.com/photo-1642552187855-388a77930fa8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    location: 'Lucknow, Uttar Pradesh',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    type: 'Government',
    rating: 4.8,
    reviewCount: 1600,
    annualFees: 10.00,
    courses: ['PGP', 'PGP-ABM'],
    degreeTypes: ['MBA', 'PhD'],
    placementPercentage: 100,
    averagePackage: 30.0,
    highestPackage: 65.0,
    nirfRanking: 6,
    facilities: ['Library', 'Hostel', 'Sports Complex'],
    accreditation: 'AMBA',
    established: 1984,
    description: 'IIM Lucknow is one of the top IIMs, known for its rigorous academics and strong corporate ties.',
    highlights: ['Top 10 Management', '100% Placement', 'AMBA Accredited'],
    topRecruiters: ['McKinsey', 'BCG', 'Amazon', 'Accenture'],
    specializations: ['Finance', 'Marketing', 'Consulting'],
    studentCount: 1100,
    facultyCount: 95,
    campusArea: 200,
    reviews: [],
  },
  {
    id: 'iit-guwahati',
    name: 'Indian Institute of Technology Guwahati',
    shortName: 'IIT Guwahati',
    logoColor: '#ef4444',
    logoInitials: 'IITG',
    image: 'https://images.unsplash.com/photo-1633987027569-a6599b632de7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    bannerImage: 'https://images.unsplash.com/photo-1633987027569-a6599b632de7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    location: 'Guwahati, Assam',
    city: 'Guwahati',
    state: 'Assam',
    type: 'Government',
    rating: 4.7,
    reviewCount: 1900,
    annualFees: 2.15,
    courses: ['Computer Science', 'Design', 'Electronics'],
    degreeTypes: ['B.Tech', 'B.Des', 'M.Tech'],
    placementPercentage: 92,
    averagePackage: 17.0,
    highestPackage: 120.0,
    nirfRanking: 7,
    facilities: ['Library', 'Hostel', 'Sports Complex'],
    accreditation: 'NAAC A',
    established: 1994,
    description: 'IIT Guwahati is known for its beautiful campus on the banks of the Brahmaputra and strong design programs.',
    highlights: ['Top 10 NIRF', 'Most Beautiful Campus', 'Strong Design Dept'],
    topRecruiters: ['Google', 'Microsoft', 'Amazon', 'Qualcomm'],
    specializations: ['Computer Science', 'Design', 'Electronics'],
    studentCount: 6000,
    facultyCount: 400,
    campusArea: 700,
    reviews: [],
  },
  {
    id: 'nit-trichy',
    name: 'National Institute of Technology Tiruchirappalli',
    shortName: 'NIT Trichy',
    logoColor: '#6366f1',
    logoInitials: 'NITT',
    image: 'https://images.unsplash.com/photo-1599043464895-0e273f94eed7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    bannerImage: 'https://images.unsplash.com/photo-1599043464895-0e273f94eed7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    location: 'Tiruchirappalli, Tamil Nadu',
    city: 'Tiruchirappalli',
    state: 'Tamil Nadu',
    type: 'Government',
    rating: 4.7,
    reviewCount: 2200,
    annualFees: 1.50,
    courses: ['Computer Science', 'Mechanical', 'Electrical'],
    degreeTypes: ['B.Tech', 'M.Tech', 'PhD'],
    placementPercentage: 90,
    averagePackage: 12.0,
    highestPackage: 40.0,
    nirfRanking: 9,
    facilities: ['Library', 'Hostel', 'Sports Complex'],
    accreditation: 'NAAC A',
    established: 1964,
    description: 'NIT Trichy is consistently ranked as the top NIT in India with excellent placements.',
    highlights: ['#1 NIT in India', 'Excellent ROI', 'Strong Alumni'],
    topRecruiters: ['Google', 'Microsoft', 'Amazon', 'L&T'],
    specializations: ['Computer Science', 'Core Engineering', 'Management'],
    studentCount: 6500,
    facultyCount: 350,
    campusArea: 800,
    reviews: [],
  },
  {
    id: 'bhu-varanasi',
    name: 'Banaras Hindu University',
    shortName: 'BHU',
    logoColor: '#f97316',
    logoInitials: 'BHU',
    image: 'https://images.unsplash.com/photo-1664273891579-22f28332f3c4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    bannerImage: 'https://images.unsplash.com/photo-1664273891579-22f28332f3c4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    location: 'Varanasi, Uttar Pradesh',
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    type: 'Government',
    rating: 4.7,
    reviewCount: 4500,
    annualFees: 0.10,
    courses: ['BA', 'B.Sc', 'B.Tech', 'MBBS'],
    degreeTypes: ['B.Tech', 'B.Sc', 'MBA'],
    placementPercentage: 85,
    averagePackage: 8.0,
    highestPackage: 120.0,
    nirfRanking: 5,
    facilities: ['Library', 'Hostel', 'Hospital'],
    accreditation: 'NAAC A',
    established: 1916,
    description: 'BHU is an internationally reputed university situated in the holy city of Varanasi.',
    highlights: ['Top 5 University', 'Low Fees', 'Largest Residential Campus'],
    topRecruiters: ['TCS', 'Infosys', 'Amazon', 'Wipro'],
    specializations: ['Arts', 'Science', 'Engineering'],
    studentCount: 30000,
    facultyCount: 1500,
    campusArea: 1300,
    reviews: [],
  },
  {
    id: 'nid-ahmedabad',
    name: 'National Institute of Design',
    shortName: 'NID Ahmedabad',
    logoColor: '#db2777',
    logoInitials: 'NID',
    image: 'https://images.unsplash.com/photo-1575688588571-966e9b61f0b7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    bannerImage: 'https://images.unsplash.com/photo-1575688588571-966e9b61f0b7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    location: 'Ahmedabad, Gujarat',
    city: 'Ahmedabad',
    state: 'Gujarat',
    type: 'Government',
    rating: 4.7,
    reviewCount: 900,
    annualFees: 4.00,
    courses: ['B.Des', 'M.Des'],
    degreeTypes: ['B.Des'],
    placementPercentage: 98,
    averagePackage: 18.0,
    highestPackage: 50.0,
    nirfRanking: 1,
    facilities: ['Design Studios', 'Library', 'Workshops'],
    accreditation: 'UGC',
    established: 1961,
    description: 'NID is internationally acclaimed as one of the foremost multi-disciplinary institutions in the field of design.',
    highlights: ['#1 Design Institute', 'Global Recognition', 'Creative Culture'],
    topRecruiters: ['Microsoft', 'Google', 'TCS', 'Wipro'],
    specializations: ['Industrial Design', 'Communication Design'],
    studentCount: 1200,
    facultyCount: 80,
    campusArea: 15,
    reviews: [],
  },
  {
    id: 'jnu-delhi',
    name: 'Jawaharlal Nehru University',
    shortName: 'JNU',
    logoColor: '#dc2626',
    logoInitials: 'JNU',
    image: 'https://images.unsplash.com/photo-1632988663082-4bac2c1847a0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    bannerImage: 'https://images.unsplash.com/photo-1632988663082-4bac2c1847a0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    location: 'New Delhi, Delhi',
    city: 'New Delhi',
    state: 'Delhi',
    type: 'Government',
    rating: 4.7,
    reviewCount: 2000,
    annualFees: 4.96,
    courses: ['BA', 'MA', 'PhD'],
    degreeTypes: ['B.Sc', 'M.Sc', 'PhD'],
    placementPercentage: 80,
    averagePackage: 10.0,
    highestPackage: 15.0,
    nirfRanking: 41,
    facilities: ['Library', 'Hostel', 'Auditorium'],
    accreditation: 'NAAC A+',
    established: 1969,
    description: 'JNU is a world-renowned university for research and teaching in social sciences and languages.',
    highlights: ['Top Arts/Science', 'Research Focus', 'Vibrant Politics'],
    topRecruiters: ['NGOs', 'Think Tanks', 'TCS'],
    specializations: ['Social Sciences', 'Languages', 'International Studies'],
    studentCount: 8000,
    facultyCount: 500,
    campusArea: 1000,
    reviews: [],
  },
  {
    id: 'klh-university',
    name: 'KLH University',
    shortName: 'KLH University',
    logoColor: '#ec4899',
    logoInitials: 'KLH',
    image: 'https://images.unsplash.com/photo-1598463035674-3ded88d65be2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    bannerImage: 'https://images.unsplash.com/photo-1598463035674-3ded88d65be2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    location: 'Hyderabad, Telangana',
    city: 'Hyderabad',
    state: 'Telangana',
    type: 'Private',
    rating: 4.5,
    reviewCount: 1200,
    annualFees: 2.50,
    courses: ['B.Tech', 'BBA', 'MBA'],
    degreeTypes: ['B.Tech', 'MBA'],
    placementPercentage: 100,
    averagePackage: 8.0,
    highestPackage: 25.0,
    nirfRanking: 28,
    facilities: ['Library', 'Hostel', 'Sports Complex'],
    accreditation: 'NAAC A++',
    established: 1980,
    description: 'KLH University is known for its modern infrastructure and strong placement records.',
    highlights: ['100% Placements', 'Modern Campus', 'Industry Tie-ups'],
    topRecruiters: ['TCS', 'Infosys', 'Wipro', 'Cognizant'],
    specializations: ['Computer Science', 'Management', 'Electronics'],
    studentCount: 15000,
    facultyCount: 800,
    campusArea: 100,
    reviews: [],
  },
  {
    id: 'amrita-vishwa',
    name: 'Amrita Vishwa Vidyapeetham',
    shortName: 'Amrita',
    logoColor: '#d97706',
    logoInitials: 'AMR',
    image: 'https://images.unsplash.com/photo-1734184489462-e8c123f2797b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    bannerImage: 'https://images.unsplash.com/photo-1734184489462-e8c123f2797b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    location: 'Coimbatore, Tamil Nadu',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    type: 'Private',
    rating: 4.3,
    reviewCount: 1700,
    annualFees: 1.90,
    courses: ['B.Tech', 'M.Tech', 'MBA'],
    degreeTypes: ['B.Tech', 'M.Tech', 'MBA'],
    placementPercentage: 90,
    averagePackage: 10.0,
    highestPackage: 15.0,
    nirfRanking: 27,
    facilities: ['Library', 'Hostel', 'Hospital'],
    accreditation: 'NAAC A+',
    established: 2003,
    description: 'Amrita Vishwa Vidyapeetham is a multi-campus, multi-disciplinary research academia.',
    highlights: ['Research Focus', 'Values Based Education', 'Global Tie-ups'],
    topRecruiters: ['Microsoft', 'TCS', 'Wipro', 'Cognizant'],
    specializations: ['Engineering', 'Medicine', 'Management'],
    studentCount: 20000,
    facultyCount: 1500,
    campusArea: 400,
    reviews: [],
  },
  {
    id: 'vit-vellore',
    name: 'Vellore Institute of Technology',
    shortName: 'VIT Vellore',
    logoColor: '#2563eb',
    logoInitials: 'VIT',
    image: 'https://images.unsplash.com/photo-1642552187855-388a77930fa8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    bannerImage: 'https://images.unsplash.com/photo-1642552187855-388a77930fa8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    location: 'Vellore, Tamil Nadu',
    city: 'Vellore',
    state: 'Tamil Nadu',
    type: 'Private',
    rating: 4.2,
    reviewCount: 4000,
    annualFees: 3.01,
    courses: ['B.Tech', 'M.Tech', 'MCA'],
    degreeTypes: ['B.Tech', 'M.Tech'],
    placementPercentage: 95,
    averagePackage: 10.0,
    highestPackage: 15.0,
    nirfRanking: 44,
    facilities: ['Library', 'Hostel', 'Sports Complex'],
    accreditation: 'NAAC A+',
    established: 1984,
    description: 'VIT Vellore is one of the most popular private engineering institutions in India.',
    highlights: ['Excellent Placements', 'Diverse Student Body', 'Modern Facilities'],
    topRecruiters: ['TCS', 'Cognizant', 'Wipro', 'Microsoft'],
    specializations: ['Computer Science', 'Electronics', 'Mechanical'],
    studentCount: 35000,
    facultyCount: 1700,
    campusArea: 372,
    reviews: [],
  },
  {
    id: 'anna-university',
    name: 'Anna University',
    shortName: 'Anna University',
    logoColor: '#b91c1c',
    logoInitials: 'AU',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Anna_university_01.jpg/3840px-Anna_university_01.jpg',
    bannerImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Anna_university_01.jpg/3840px-Anna_university_01.jpg',
    location: 'Chennai, Tamil Nadu',
    city: 'Chennai',
    state: 'Tamil Nadu',
    type: 'Government',
    rating: 4.2,
    reviewCount: 2500,
    annualFees: 3.62,
    courses: ['B.Tech', 'B.E', 'M.Tech'],
    degreeTypes: ['B.Tech', 'M.Tech', 'PhD'],
    placementPercentage: 85,
    averagePackage: 10.0,
    highestPackage: 15.0,
    nirfRanking: 3,
    facilities: ['Library', 'Hostel', 'Sports Complex'],
    accreditation: 'NAAC A+',
    established: 1978,
    description: 'Anna University is a premier state university highly regarded for its engineering programs.',
    highlights: ['Top State University', 'Strong Alumni', 'Research Centers'],
    topRecruiters: ['TCS', 'Cognizant', 'Infosys', 'Ford'],
    specializations: ['Engineering', 'Technology', 'Architecture'],
    studentCount: 15000,
    facultyCount: 800,
    campusArea: 189,
    reviews: [],
  }
];

export const popularSearches = [
  'Computer Science Engineering',
  'IIT Colleges Delhi',
  'Top Engineering Bangalore',
  'Government Colleges Maharashtra',
];

export const featuredColleges = colleges.slice(0, 3);
export const trendingColleges = colleges.slice(0, 3);
